# Generated by Django 4.2.16 on 2024-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgs', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=10000)),
                ('userId', models.IntegerField()),
                ('type', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
