# Generated by Django 4.2.16 on 2024-11-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategy_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='imgs',
            field=models.JSONField(max_length=1000),
        ),
    ]
