# Generated by Django 4.2.16 on 2024-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('scenicId', models.IntegerField()),
                ('reserveTime', models.DateTimeField()),
                ('lastReserveTime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('evaluationId', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
