# Generated by Django 4.2.16 on 2024-11-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('scenicId', models.IntegerField()),
                ('reserveTime', models.DateTimeField()),
                ('lastReserveTime', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('evaluationId', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Reserver',
        ),
    ]
