# Generated by Django 4.2.16 on 2024-11-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
