# Generated by Django 4.2.16 on 2024-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0002_alter_scenic_score_alter_scenic_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic',
            name='imgs',
            field=models.JSONField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scenic',
            name='tags',
            field=models.JSONField(max_length=200),
        ),
    ]
