# Generated by Django 4.2.16 on 2024-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicStar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenicId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
