from django.urls import path

from . import views

urlpatterns = [
    path('api/user/login', views.user_login),
    path('api/user/register', views.user_register),
    path('api/user/current', views.user_current),
    path('api/user/logout', views.user_logout),
    path('api/user/update', views.user_update),
    path('api/user/list', views.user_list),
    path('api/user/delete/<int:id>', views.user_delete),
    path('api/user/add', views.user_add),
    path('api/scenic/add', views.scenic_add),
    path('api/scenic/list', views.scenic_list),
    path('api/scenic/<int:id>', views.scenic_detail),
    path('api/scenic/delete/<int:id>', views.scenic_delete),
    path('api/scenic/update/<int:id>', views.scenic_update),
    path('api/strategy/add', views.strategy_add),
    path('api/strategy/list', views.strategy_list),
    path('api/strategy/delete/<int:id>', views.strategy_delete),
    path('api/strategy/update/<int:id>', views.strategy_update),
    path('api/strategy/<int:id>', views.strategy_detail),
    path('api/reserve/add', views.reserve_add),
    path('api/reserve/get/my', views.reserve_get_my),
    path('api/reserve/get/all', views.reserve_get_all),
    path('api/reserve/<int:id>', views.reserve_detail),
    path('api/evaluation/add', views.evaluation_add),
    path('api/evaluation/<int:id>', views.evaluation_detail),
    path('api/scenic/star/add', views.scenic_star_add),
    path('api/scenic/star/delete', views.scenic_star_delete),
    path('api/scenic/starred', views.scenic_starred),
    path('api/strategy/star/add', views.strategy_star_add),
    path('api/strategy/star/delete', views.strategy_star_delete),
    path('api/scenic_star/list/my', views.get_scenic_star),
    path('api/scenic_star/add', views.scenic_star_add),
    path('api/scenic_star/delete', views.scenic_star_delete),
    path('api/scenic_starred', views.scenic_starred),
    path('api/strategy_star/list/my', views.get_strategy_star),
    path('api/strategy_star/add', views.strategy_star_add),
    path('api/strategy_star/delete', views.strategy_star_delete),
    path('api/strategy_starred', views.strategy_starred),
]
